name: GH Pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.85.0"
          extended: true
      
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Update theme
        run: git submodule update --init --recursive

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public